output gcov version

diff --git a/.github/workflows/xahau-ga-nix.yml b/.github/workflows/xahau-ga-nix.yml
--- a/.github/workflows/xahau-ga-nix.yml
+++ b/.github/workflows/xahau-ga-nix.yml
@@ -85,6 +85,7 @@ jobs:
           
           # Check gcovr for coverage jobs
           if [ "${{ matrix.job_type }}" = "coverage" ]; then
+            which gcov && gcov --version || echo "gcov not found"
             which gcovr && gcovr --version || echo "gcovr not found"
           fi
           
